use_degrees = true

[image]
type = "ppm"

output_fn 	= "output.ppm"
width 		= 1024
height 		= 1024


[camera]
type = "perspective"

width 		= 1024
height 		= 1024

eye = [280.0, 275.0, -330.0]
at  = [280.0, 265.0, 0.0]
up  = [0.0, 1.0, 0.0]
fov_w = 90.0
fov_h = 90.0


[scene]

input_fn  = "models/cornell_box_VI.obj"

light_ids = ["light0", "light1"]

	[scene.light0]
	type = "ambient"

	color = [0.05, 0.05, 0.05]

	[scene.light1]
	type = "point"

	color = [0.65, 0.65, 0.65]
	pos = [288.0, 508.0, 282.0]


[shader]
type = "whitted"

bg = [0.05, 0.05, 0.55]


[renderer]
type = "standard"
