use_degrees = true

[image]
type = "ppm"

output_fn     = "output.ppm"
width         = 1024
height        = 1024

threads     = 16


[camera]
type = "perspective"

width         = 1024
height        = 1024

eye = [280.0, 275.0, -330.0]
at  = [280.0, 265.0, 0.0]
up  = [0.0, 1.0, 0.0]
fov_w = 90.0
fov_h = 90.0


[scene]

input_fn  = "models/cornell_box_VI.obj"

#light_ids = ["l3", "l4", "l5", "l6"]
#light_ids = ["l3", "l4"]
#light_ids = ["l0", "l1", "l3", "l7", "l9", "l5"]
light_ids = ["l1"]
#light_ids = ["l1", "l2", "l3", "l4", "l5", "l6", "l7", "l9", "l10", "l8"]
#light_ids = ["l0", "l1", "l2", "l3", "l4", "l5", "l6", "l7", "l9", "l10", "l8"]

    [scene.l0]
    type = "ambient"

    color = [0.05, 0.05, 0.05]
    #color = [0.05, 0.01, 0.01]


    [scene.l1]
    type = "area"

    power = [0.9, 0.9, 0.9]
    v1 = [328.0, 548.7, 329.6]
    v2 = [228.0, 548.7, 329.6]
    v3 = [328.0, 548.7, 229.6]

    [scene.l2]
    type = "area"

    power = [1.0, 1.0, 1.0]
    v1 = [228.0, 548.7, 229.6]
    v2 = [328.0, 548.7, 229.6]
    v3 = [228.0, 548.7, 329.6]

    [scene.l3]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [503.0, 548.7, 454.6]
    v2 = [453.0, 548.7, 454.6]
    v3 = [503.0, 548.7, 404.6]

    [scene.l4]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [453.0, 548.7, 404.6]
    v2 = [503.0, 548.7, 404.6]
    v3 = [453.0, 548.7, 454.6]

    [scene.l5]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [503.0, 548.7, 154.6]
    v2 = [453.0, 548.7, 154.6]
    v3 = [503.0, 548.7, 104.6]

    [scene.l6]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [453.0, 548.7, 104.6]
    v2 = [503.0, 548.7, 104.6]
    v3 = [453.0, 548.7, 154.6]

    [scene.l7]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [103.0, 548.7, 154.6]
    v2 = [53.0, 548.7, 154.6]
    v3 = [103.0, 548.7, 104.6]

    [scene.l8]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [53.0, 548.7, 104.6]
    v2 = [103.0, 548.7, 104.6]
    v3 = [53.0, 548.7, 154.6]

    [scene.l9]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [103.0, 548.7, 454.6]
    v2 = [53.0, 548.7, 454.6]
    v3 = [103.0, 548.7, 404.6]

    [scene.l10]
    type = "area"

    power = [0.5, 0.5, 0.5]
    v1 = [53.0, 548.7, 404.6]
    v2 = [103.0, 548.7, 404.6]
    v3 = [53.0, 548.7, 454.6]


[shader]
type = "distributed"

bg = [0.05, 0.05, 0.55]

max_depth = 4

monte_carlo = true


[renderer]
type = "standard"

spp = 16
